### ISSUE TITLE
Allow newer versions of nette/forms

### ISSUE THREAD

**Issue by racinmat** [contributte/forms-bootstrap#56]
Running `composer require contributte/forms-bootstrap`, composer raises
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires contributte/forms-bootstrap ^0.4.2 -> satisfiable by contributte/forms-bootstrap[v0.4.2].
    - contributte/forms-bootstrap v0.4.2 requires nette/forms 3.1.3 -> found nette/forms[v3.1.3] but the package is fixed to v3.1.5 (lock file version) by a partial update and that version does not match. Make sure yo
u list it as an argument for the update command.
```

is there a reason why nette/forms is locked to 3.1.3 and ^3.1.3 is not allowed?

Installing `composer require contributte/forms-bootstrap:*` gave me `contributte/forms-bootstrap:0.3.1` as compatible with `nette/forms 3.1.5`, which is the last version with ^ costraint. See https://github.com/contributte/forms-bootstrap/compare/v0.3.1...v0.3.2#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34

Should I make PR for it?

**Comment by dakorpar** [comment]
Hi, nope, package is on purpose locked on specific versions of nette forms to avoid possible conflicts. release 0.5 is now locked to 3.1.6

**Comment by racinmat** [comment]
I see, so if I want to use this package, I need to use nette/forms either 3.1.3 or 3.1.6, nothing in between?

**Comment by dakorpar** [comment]
> I see, so if I want to use this package, I need to use nette/forms either 3.1.3 or 3.1.6, nothing in between?

Usually, plan is to have version for every nette version, but since it was summer time and me being really buisy that didn't happen.
However you can allways use AS ( https://getcomposer.org/doc/articles/aliases.md ) in composer and install whichever version of nette\forms you want.
There already were problem in past because on minor change, some function signature changed and everything failed on our end. I don't want to crash production because of such thing. 

so with new version you can say 3.1.5 as 3.1.6 for example...

**Comment by racinmat** [comment]
I see, thanks for the reaponse. I understand maintaining it for every patch version is quite time consuming.
