### ISSUE TITLE
Release new version supporting nette/forms 3.1.8

### ISSUE THREAD

**Issue by foxycode** [contributte/forms-bootstrap#73]
I see support for `nette/forms` version `3.1.8` is already merged to master. Can you please release new version?

Also, is there still need to limit this package to specific version? Wouldn't be `~3.1.7` better?

**Comment by f3l1x** [comment]
~3.1.7 sounds good to me, please prepare PR.

**Comment by foxycode** [comment]
@f3l1x I thought I have access, can you please allow me push new branches?

**Comment by dakorpar** [comment]
No, please don't do that. This library heavily uses some internal code from nette/forms and because of that it's allways strict on using exact minor version. Having in composer ~ for nette forms is highly dangerous since it could potentially crash current release.

**Comment by dakorpar** [comment]
0.5.4 released. I wanted to add build for 8.2 before that and made support for it, but you're rushing into it. You can allways just put ^0.6 in your composer and you'll be on master if it's critical.

**Comment by foxycode** [comment]
@dakorpar Can you please tell which internal things? Maybe I can speak with David Grudl to fix these things in `nette/forms`

**Comment by dakorpar** [comment]
There's noting to fix, library itself is using some methods that are marked as @internal those methods can be changed at any minor version, because of nature of this library it's actually built on top of nette/forms and doing some changes on it, it is very dangerous not to have it like that and in the end there's really no need for this.
