### ISSUE TITLE
Update for nette/forms version 3.1.10 

### ISSUE THREAD

**Issue by mokrys** [contributte/forms-bootstrap#79]
Please update for new nette/forms version 3.1.10. THX

**Comment by dakorpar** [comment]
It's in master, try to test if all ok and let me know...
You can easily update with "^0.6" version constraint.
I see some BCs on nette/forms side ATM and because of that I'm postponing release until I make sure all is good. For  example radio buttons  optionvalues in array has to be strings now (before it could be number types as well)

**Comment by mokrys** [comment]
Thank you, everything looks fine.

**Comment by simPod** [comment]
Same here

**Comment by BigOHenry** [comment]
Is it possible to make version with nette/forms version 3.1.10 or 3.1.11 please? Current version requires nette/forms 3.1.9 and that version does not exists.
