### ISSUE TITLE
Support for nette/forms 3.1.14

### ISSUE THREAD

**Issue by matoni555** [contributte/forms-bootstrap#86]
Can you please add support for current release of nette/forms (3.1.15)?

Thank you

**Comment by f3l1x** [comment]
@dakorpar Please, unlock for all 3.1.x, it does not make any sense to update every two weeks.

**Comment by dakorpar** [comment]
@f3l1x that will lead to MANY sites crashed after composer update. Nette/forms has BC every now and then and this library is also using internal functions that can change at any time. I did that mistake in beggining, won't do it again.

**Comment by f3l1x** [comment]
OK.

**Comment by dakorpar** [comment]
Hmm, this is a bit tricky now... We already have Date and Datetime control in. Now if I switch to nette one it's breaking change and if I introduce a new different function for nette native controls interface won't be almost the same with nette forms anymore... I'll have to investigate more...
@matoni555 feel free to send PR, this will probably be on hold for  few more days if it's waiting for me. just changing composer.json IS NOT an option.

**Comment by H0w4rd** [comment]
Hi, any idea how to solve this problem?

**Comment by darkWolf-PR** [comment]
@dakorpar I´d say using the Nette ones is the right way, Dfferent way can just add more problems. Declare new version with breaking change. If Nette/Forms can do BCs and it does not matter that sites crash after composer update, there is no point going around with component that expands on NetteForms. And no one should be running composer update on production...

**Comment by dakorpar** [comment]
@H0w4rd I don't have much room there... I have to stay compatible with nette forms, which means compatibility with nette/forms 3.1.14 will include HUGE BCs...
I've added new date/datetime/time/color controls now and had to rename current addDate and addDateTime to addBootstrapDate and addBootstrapDateTime... That's only thing I can do since my container basically "inherits" nette container and all calls need to be compatible... I'll do some testing tomorrow...
you can all also try it out with including:
"contributte/forms-bootstrap": "v3.1.14.x-dev",

**Comment by dakorpar** [comment]
compatibility with 3.1.15 done and released. 3.2.0 is also ready and will be released probably tomorrow.
closing this
